export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_PRICE_RANGE: "INVALID_PRICE_RANGE",
  PLACE_NOT_FOUND: "PLACE_NOT_FOUND",
  PACKAGE_NOT_FOUND: "PACKAGE_NOT_FOUND",
  SLUG_ALREADY_EXISTS: "SLUG_ALREADY_EXISTS",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
